"""add suites

Revision ID: 23da19f08a45
Revises: 2b312c1adaca
Create Date: 2026-08-02 22:51:23.629274

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23da19f08a45"
down_revision: str | Sequence[str] | None = "2b312c1adaca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("path", sa.String(length=2000), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["suites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_suites_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_suites_path"), ["path"], unique=False)
        batch_op.create_index(batch_op.f("ix_suites_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suites_project_id"))
        batch_op.drop_index(batch_op.f("ix_suites_path"))
        batch_op.drop_index(batch_op.f("ix_suites_parent_id"))

    op.drop_table("suites")
    # ### end Alembic commands ###
