"""add run jobs

Revision ID: 281abf25467a
Revises: 8d0b1991aa58
Create Date: 2026-08-13 01:48:43.941223

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "281abf25467a"
down_revision: str | Sequence[str] | None = "8d0b1991aa58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=False),
        sa.Column("git_ref", sa.String(length=200), nullable=False),
        sa.Column("resolved_sha", sa.String(length=40), nullable=True),
        sa.Column("command", sa.String(length=500), nullable=False),
        sa.Column("case_keys_json", sa.JSON(), nullable=False),
        sa.Column("claimed_by", sa.String(length=200), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("output_tail", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_jobs_run_id"), ["run_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_run_jobs_status"), ["status"], unique=False)

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("repo_url", sa.String(length=500), nullable=True))
        batch_op.add_column(
            sa.Column("default_ref", sa.String(length=200), nullable=False, server_default="main")
        )
        batch_op.add_column(sa.Column("test_command", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("test_command")
        batch_op.drop_column("default_ref")
        batch_op.drop_column("repo_url")

    with op.batch_alter_table("run_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_run_jobs_run_id"))

    op.drop_table("run_jobs")
    # ### end Alembic commands ###
