"""add test cases, versions, and tags

Revision ID: 57c7a6b07535
Revises: 23da19f08a45
Create Date: 2026-08-02 23:04:58.400917

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57c7a6b07535"
down_revision: str | Sequence[str] | None = "23da19f08a45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_tags_project_name"),
    )
    op.create_table(
        "test_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=True),
        sa.Column("case_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("execution_type", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column("preconditions", sa.Text(), nullable=True),
        sa.Column("steps_json", sa.JSON(), nullable=False),
        sa.Column("expected_result", sa.Text(), nullable=True),
        sa.Column("current_version_no", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("updated_by", sa.String(length=200), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["suites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_cases_case_key"), ["case_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_test_cases_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_cases_suite_id"), ["suite_id"], unique=False)

    op.create_table(
        "test_case_tags",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["test_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("case_id", "tag_id"),
    )
    op.create_table(
        "test_case_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("test_case_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("execution_type", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=4), nullable=False),
        sa.Column("preconditions", sa.Text(), nullable=True),
        sa.Column("steps_json", sa.JSON(), nullable=False),
        sa.Column("expected_result", sa.Text(), nullable=True),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_case_id", "version_no", name="uq_case_version_no"),
    )
    with op.batch_alter_table("test_case_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_test_case_versions_test_case_id"), ["test_case_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_case_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_case_versions_test_case_id"))

    op.drop_table("test_case_versions")
    op.drop_table("test_case_tags")
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_cases_suite_id"))
        batch_op.drop_index(batch_op.f("ix_test_cases_project_id"))
        batch_op.drop_index(batch_op.f("ix_test_cases_case_key"))

    op.drop_table("test_cases")
    op.drop_table("tags")
    # ### end Alembic commands ###
