"""add test plans

Revision ID: 71e498471fe9
Revises: 4930f85ddb17
Create Date: 2026-08-04 13:39:56.943274

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71e498471fe9"
down_revision: str | Sequence[str] | None = "4930f85ddb17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("milestone", sa.String(length=100), nullable=True),
        sa.Column("environment", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("updated_by", sa.String(length=200), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_test_plans_environment"), ["environment"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_test_plans_milestone"), ["milestone"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_plans_project_id"), ["project_id"], unique=False)

    op.create_table(
        "test_plan_cases",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("test_case_id", sa.String(length=36), nullable=False),
        sa.Column("test_case_version_id", sa.String(length=36), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["test_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_case_version_id"],
            ["test_case_versions.id"],
        ),
        sa.PrimaryKeyConstraint("plan_id", "test_case_id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_plan_id"), ["plan_id"], unique=False)
        batch_op.create_foreign_key("fk_runs_plan_id_test_plans", "test_plans", ["plan_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_runs_plan_id_test_plans", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_runs_plan_id"))

    op.drop_table("test_plan_cases")
    with op.batch_alter_table("test_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_plans_project_id"))
        batch_op.drop_index(batch_op.f("ix_test_plans_milestone"))
        batch_op.drop_index(batch_op.f("ix_test_plans_environment"))

    op.drop_table("test_plans")
    # ### end Alembic commands ###
