/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cases/{case_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_cases__case_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Case */
        patch: operations["update_case_api_cases__case_key__patch"];
        trace?: never;
    };
    "/api/cases/{case_key}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Case */
        post: operations["archive_case_api_cases__case_key__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_key}/automation-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Automation Links */
        get: operations["list_automation_links_api_cases__case_key__automation_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_key}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Tags */
        put: operations["set_tags_api_cases__case_key__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_key}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_cases__case_key__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Plan */
        post: operations["archive_plan_api_plans__plan_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plan Cases */
        get: operations["list_plan_cases_api_plans__plan_id__cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plan Runs */
        get: operations["list_plan_runs_api_plans__plan_id__runs_get"];
        put?: never;
        /** Execute Plan */
        post: operations["execute_plan_api_plans__plan_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_key}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_projects__project_key__cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_projects__project_key__cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_key}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_projects__project_key__plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_projects__project_key__plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_key}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Runs */
        get: operations["list_project_runs_api_projects__project_key__runs_get"];
        put?: never;
        /** Open Run */
        post: operations["open_run_api_projects__project_key__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_key}/runs/import-junit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Junit */
        post: operations["import_junit_api_projects__project_key__runs_import_junit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_key}/suites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suites */
        get: operations["list_suites_api_projects__project_key__suites_get"];
        put?: never;
        /** Create Suite */
        post: operations["create_suite_api_projects__project_key__suites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cases/{case_key}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Case Manually */
        post: operations["execute_case_manually_api_runs__run_id__cases__case_key__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Run */
        post: operations["complete_run_api_runs__run_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Results */
        get: operations["list_results_api_runs__run_id__results_get"];
        put?: never;
        /** Ingest Results */
        post: operations["ingest_results_api_runs__run_id__results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suites/{suite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Suite */
        patch: operations["update_suite_api_suites__suite_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutomationLinkOut */
        AutomationLinkOut: {
            /** Active */
            active: boolean;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Framework */
            framework: string;
            /** Id */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Test Identifier */
            test_identifier: string;
        };
        /** CaseCreate */
        CaseCreate: {
            /**
             * Execution Type
             * @default automated
             * @enum {string}
             */
            execution_type: "manual" | "automated";
            /** Expected Result */
            expected_result?: string | null;
            /** Preconditions */
            preconditions?: string | null;
            /**
             * Priority
             * @default p2
             * @enum {string}
             */
            priority: "p0" | "p1" | "p2" | "p3";
            /** Steps */
            steps?: components["schemas"]["Step"][];
            /** Suite Id */
            suite_id?: string | null;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
        };
        /**
         * CaseFilter
         * @description Mirrors the case-list query parameters, so one mental model covers both.
         */
        CaseFilter: {
            /** Execution Type */
            execution_type?: ("manual" | "automated") | null;
            /** Q */
            q?: string | null;
            /** Status */
            status?: string | null;
            /** Suite Id */
            suite_id?: string | null;
            /** Tag */
            tag?: string | null;
        };
        /** CaseOut */
        CaseOut: {
            /** Archived At */
            archived_at: string | null;
            /** Case Key */
            case_key: string;
            /** Created By */
            created_by: string;
            /** Current Version No */
            current_version_no: number;
            /** Execution Type */
            execution_type: string;
            /** Expected Result */
            expected_result: string | null;
            /** Id */
            id: string;
            /** Owner */
            owner: string | null;
            /** Preconditions */
            preconditions: string | null;
            /** Priority */
            priority: string;
            /** Project Id */
            project_id: string;
            /** Status */
            status: string;
            /** Steps */
            steps: components["schemas"]["Step"][];
            /** Suite Id */
            suite_id: string | null;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /** Updated By */
            updated_by: string;
        };
        /** CaseUpdate */
        CaseUpdate: {
            /** Change Note */
            change_note?: string | null;
            /** Execution Type */
            execution_type?: ("manual" | "automated") | null;
            /** Expected Result */
            expected_result?: string | null;
            /** Expected Version No */
            expected_version_no: number;
            /** Owner */
            owner?: string | null;
            /** Preconditions */
            preconditions?: string | null;
            /** Priority */
            priority?: ("p0" | "p1" | "p2" | "p3") | null;
            /** Status */
            status?: ("draft" | "active" | "deprecated") | null;
            /** Steps */
            steps?: components["schemas"]["Step"][] | null;
            /** Suite Id */
            suite_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** CaseVersionOut */
        CaseVersionOut: {
            /** Change Note */
            change_note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Execution Type */
            execution_type: string;
            /** Expected Result */
            expected_result: string | null;
            /** Preconditions */
            preconditions: string | null;
            /** Priority */
            priority: string;
            /** Steps */
            steps: components["schemas"]["Step"][];
            /** Title */
            title: string;
            /** Version No */
            version_no: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestSummary */
        IngestSummary: {
            /** Archived Case Results */
            archived_case_results: number;
            /** By Outcome */
            by_outcome: {
                [key: string]: number;
            };
            /** Recorded */
            recorded: number;
            /** Resolved */
            resolved: number;
            /** Run Id */
            run_id: string;
            /** Unresolved */
            unresolved: number;
        };
        /** JUnitImport */
        JUnitImport: {
            /** External Id */
            external_id: string;
            /** Name */
            name?: string | null;
            /** Xml */
            xml: string;
        };
        /** ManualExecute */
        ManualExecute: {
            /** Duration Ms */
            duration_ms?: number | null;
            /** Notes */
            notes?: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "passed" | "failed" | "skipped" | "error" | "blocked";
        };
        /** PlanCaseOut */
        PlanCaseOut: {
            /** Case Key */
            case_key: string;
            /** Execution Type */
            execution_type: string;
            /** Position */
            position: number;
            /** Test Case Version Id */
            test_case_version_id: string | null;
            /** Title */
            title: string;
        };
        /** PlanCreate */
        PlanCreate: {
            /** Case Keys */
            case_keys?: string[];
            /** Description */
            description?: string | null;
            /** Environment */
            environment?: string | null;
            filter?: components["schemas"]["CaseFilter"] | null;
            /** Milestone */
            milestone?: string | null;
            /** Name */
            name: string;
        };
        /** PlanOut */
        PlanOut: {
            /** Archived At */
            archived_at: string | null;
            /** Case Count */
            case_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Description */
            description: string | null;
            /** Environment */
            environment: string | null;
            /** Id */
            id: string;
            /** Milestone */
            milestone: string | null;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string;
            /** Status */
            status: string;
        };
        /** PlanProgress */
        PlanProgress: {
            /** By Outcome */
            by_outcome: {
                [key: string]: number;
            };
            /** Cases With Result */
            cases_with_result: number;
            /** Cases Without Result */
            cases_without_result: string[];
            /** Total Cases */
            total_cases: number;
        };
        /** PlanRunCreate */
        PlanRunCreate: {
            /** External Id */
            external_id?: string | null;
            /** Name */
            name?: string | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Description */
            description?: string | null;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Case Seq */
            case_seq: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** ResultBatch */
        ResultBatch: {
            /** Results */
            results: components["schemas"]["ResultIn"][];
        };
        /** ResultIn */
        ResultIn: {
            /** Attachments */
            attachments?: string[];
            /** Case Key */
            case_key?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Failure Message */
            failure_message?: string | null;
            /** Failure Type */
            failure_type?: string | null;
            /**
             * Framework
             * @default pytest
             */
            framework: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "passed" | "failed" | "skipped" | "error" | "blocked";
            /** Stack Trace */
            stack_trace?: string | null;
            /** Test Identifier */
            test_identifier: string;
        };
        /** ResultOut */
        ResultOut: {
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Failure Message */
            failure_message: string | null;
            /** Failure Type */
            failure_type: string | null;
            /** Id */
            id: string;
            /** Outcome */
            outcome: string;
            /** Test Case Id */
            test_case_id: string | null;
            /** Test Case Version Id */
            test_case_version_id: string | null;
            /** Test Identifier */
            test_identifier: string;
            /** Unresolved Case Key */
            unresolved_case_key: string | null;
        };
        /** RunCreate */
        RunCreate: {
            /** Ci Metadata */
            ci_metadata?: {
                [key: string]: unknown;
            };
            /** External Id */
            external_id: string;
            /** Name */
            name?: string | null;
            /**
             * Source
             * @default local
             * @enum {string}
             */
            source: "ci" | "local" | "manual" | "runner";
        };
        /** RunListItemOut */
        RunListItemOut: {
            /** By Outcome */
            by_outcome: {
                [key: string]: number;
            };
            /** Completed At */
            completed_at: string | null;
            /** Created By */
            created_by: string;
            /** External Id */
            external_id: string;
            /** Id */
            id: string;
            /** Name */
            name: string | null;
            /** Plan Id */
            plan_id: string | null;
            /** Project Id */
            project_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Total Results */
            total_results: number;
        };
        /** RunOut */
        RunOut: {
            /** Completed At */
            completed_at: string | null;
            /** Created By */
            created_by: string;
            /** External Id */
            external_id: string;
            /** Id */
            id: string;
            /** Name */
            name: string | null;
            /** Plan Id */
            plan_id: string | null;
            /** Project Id */
            project_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /** By Outcome */
            by_outcome: {
                [key: string]: number;
            };
            /** Completed At */
            completed_at: string | null;
            /** Created By */
            created_by: string;
            /** External Id */
            external_id: string;
            /** Id */
            id: string;
            /** Name */
            name: string | null;
            /** Plan Id */
            plan_id: string | null;
            plan_progress?: components["schemas"]["PlanProgress"] | null;
            /** Project Id */
            project_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Total Results */
            total_results: number;
            /** Unresolved Count */
            unresolved_count: number;
        };
        /** Step */
        Step: {
            /** Action */
            action: string;
            /**
             * Expected
             * @default
             */
            expected: string;
        };
        /** SuiteCreate */
        SuiteCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** SuiteOut */
        SuiteOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Path */
            path: string;
            /** Position */
            position: number;
            /** Project Id */
            project_id: string;
        };
        /** SuiteUpdate */
        SuiteUpdate: {
            /**
             * Move
             * @default false
             */
            move: boolean;
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** TagsSet */
        TagsSet: {
            /** Tags */
            tags: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_case_api_cases__case_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_cases__case_key__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                case_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_case_api_cases__case_key__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                case_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_automation_links_api_cases__case_key__automation_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationLinkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tags_api_cases__case_key__tags_put: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                case_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_cases__case_key__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_plan_api_plans__plan_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_cases_api_plans__plan_id__cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanCaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_runs_api_plans__plan_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_plan_api_plans__plan_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_projects__project_key__cases_get: {
        parameters: {
            query?: {
                suite_id?: string | null;
                tag?: string | null;
                status?: string | null;
                execution_type?: string | null;
                q?: string | null;
            };
            header?: never;
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_projects__project_key__cases_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_projects__project_key__plans_get: {
        parameters: {
            query?: {
                status?: string | null;
                milestone?: string | null;
                environment?: string | null;
            };
            header?: never;
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_projects__project_key__plans_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_runs_api_projects__project_key__runs_get: {
        parameters: {
            query?: {
                status?: string | null;
                source?: string | null;
                plan_id?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_run_api_projects__project_key__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_junit_api_projects__project_key__runs_import_junit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JUnitImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suites_api_projects__project_key__suites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_suite_api_projects__project_key__suites_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_case_manually_api_runs__run_id__cases__case_key__execute_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                run_id: string;
                case_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualExecute"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_run_api_runs__run_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_results_api_runs__run_id__results_get: {
        parameters: {
            query?: {
                outcome?: string | null;
                case_key?: string | null;
                unresolved?: boolean | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_results_api_runs__run_id__results_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_suite_api_suites__suite_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-actor"?: string | null;
            };
            path: {
                suite_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
